#
# ~/.bashrc

# disable less history file
export LESSHISTFILE=-

# history
export HISTIGNORE="ls *:cd *"
export HISTSIZE=10000

# git
export GIT_EDITOR=nvim

# paths
export XDG_CONFIG_HOME="${HOME}/.config"
export RARCH_ROOT="${HOME}/rarch"
export RARCH_DOTFILES="${RARCH_ROOT}/dotfiles"
export RARCH_SCRIPTS="${RARCH_ROOT}/scripts"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# aliases
alias ls='ls -lah --color=auto'
alias duf='du -h --max-depth=1 | sort -h'
alias tree='tree -Cha'
alias grep='grep --color=auto'
alias vim='nvim'

# prompt
PS1='[\A] (\u@\h) \w \$ '
